services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT
      - KEYCLOAK_BASE_URL
      - KEYCLOAK_USER_NAME
      - KEYCLOAK_PASSWORD
      - KEYCLOAK_REALM
      - KEYCLOAK_CLIENT_ID
      - KEYCLOAK_APPLICATION_REALM
      - KEYCLOAK_CLIENT_SECRET
      - DB_URL
      - SMTP
      - EMAIL
    networks:
      - backend

networks:
  backend:
    driver: bridge