// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"database/sql"
	"marketplace/internal/config"
	http2 "marketplace/internal/core/customer/api/http"
	"marketplace/internal/core/customer/repository"
	customer2 "marketplace/internal/core/customer/service"
	http4 "marketplace/internal/core/order/api/http"
	repository3 "marketplace/internal/core/order/repository"
	"marketplace/internal/core/order/service"
	http3 "marketplace/internal/core/product/api/http"
	repository2 "marketplace/internal/core/product/repository"
	service2 "marketplace/internal/core/product/service"
	"marketplace/internal/infra/auth"
	"marketplace/internal/infra/auth/basic"
	http6 "marketplace/internal/infra/auth/basic/api/http"
	repository4 "marketplace/internal/infra/auth/basic/repository"
	service3 "marketplace/internal/infra/auth/basic/service"
	http5 "marketplace/internal/infra/authz/permission/api/http"
	"marketplace/internal/infra/authz/permission/repository"
	permission2 "marketplace/internal/infra/authz/permission/service"
	resource2 "marketplace/internal/infra/authz/resource/repository"
	"marketplace/internal/infra/authz/resource/service"
	role3 "marketplace/internal/infra/authz/role/api/http"
	"marketplace/internal/infra/authz/role/repository"
	role2 "marketplace/internal/infra/authz/role/service"
	"marketplace/internal/infra/db"
	"marketplace/internal/infra/http"
	"marketplace/internal/infra/idempotency"
	"marketplace/internal/infra/user/api/http"
	"marketplace/internal/infra/user/repository"
	"marketplace/internal/infra/user/service"
	"marketplace/pkg/http/middleware"
	"net/http"
)

// Injectors from wire_inject.go:

// InitializeApp wires up the application dependencies.
func InitializeApp(cfg *config.Config) (*Application, error) {
	db, err := provideDB(cfg)
	if err != nil {
		return nil, err
	}
	repository := provideUserRepository(db)
	txManager := provideTxManager(db)
	roleRepository := provideRoleRepository(db, txManager)
	phoneValidationRepository := providePhoneValidationRepository(db)
	phoneValidationService := providePhoneValidationService(phoneValidationRepository)
	registrationTokenRepository := provideRegistrationTokenRepository(db)
	registrationTokenService := provideRegistrationTokenService(registrationTokenRepository)
	service := provideUserService(repository, roleRepository, phoneValidationService, registrationTokenService)
	permissionRepository := providePermissionRepository(db)
	roleService := provideRoleService(roleRepository, permissionRepository)
	userPermissionChecker := provideUserPermissionChecker(repository, roleService)
	userHandler := provideUserHandler(service, userPermissionChecker)
	roleHandler := provideRoleHandler(roleService)
	resourceRepository := provideResourceRepository(db, txManager)
	resourceService := provideResourceService(resourceRepository)
	permissionService := providePermissionService(permissionRepository, resourceService)
	permissionHandler := providePermissionHandler(permissionService)
	credentialRepository := provideBasicAuthRepository(db)
	serviceService := provideBasicAuthService(credentialRepository, service, userPermissionChecker)
	handler := provideBasicAuthHandler(serviceService)
	customerRepository := provideCustomerRepository(db)
	customerService := provideCustomerService(customerRepository)
	customerHandler := provideCustomerHandler(customerService)
	repositoryRepository := provideProductRepository(db)
	service2 := provideProductService(repositoryRepository)
	productHandler := provideProductHandler(service2)
	repository2 := provideOrderRepository(db)
	orderService := provideOrderService(repository2)
	orderHandler := provideOrderHandler(orderService)
	store := provideIdempotencyStore(db)
	idempotencyMiddleware := provideIdempotencyMiddleware(store)
	adapter := provideBasicAuthAdapter(serviceService)
	authMiddleware := provideAuthMiddleware(cfg, adapter, service)
	authorizationMiddleware := provideAuthorizationMiddleware(resourceService, userPermissionChecker)
	registrationTokenAdapter := provideRegistrationTokenAdapter(registrationTokenService)
	registrationTokenMiddleware := provideRegistrationTokenMiddleware(registrationTokenAdapter)
	appHttpMiddleware := provideHTTPMiddleware(idempotencyMiddleware, authMiddleware, authorizationMiddleware, registrationTokenMiddleware)
	httpHandler := provideHTTPHandler(userHandler, roleHandler, permissionHandler, handler, customerHandler, productHandler, orderHandler, appHttpMiddleware)
	server := provideHTTPServer(cfg, httpHandler)
	appApplicationInfrastructure := provideApplicationInfrastructure(cfg, db, server)
	appApplicationServices := provideApplicationServices(service, roleService, permissionService, resourceService, serviceService, customerService, service2, orderService)
	appApplicationHandlers := provideApplicationHandlers(userHandler, roleHandler, permissionHandler, customerHandler, productHandler, orderHandler)
	application := provideApplication(appApplicationInfrastructure, appApplicationServices, appApplicationHandlers)
	return application, nil
}

// wire_inject.go:

// provideDB creates a DB connection.
func provideDB(cfg *config.Config) (*sql.DB, error) {
	return db.NewPostgres(cfg.DB.DSN())
}

// provideTxManager creates a transaction manager for the provided DB.
func provideTxManager(dbConn *sql.DB) db.TxManager {
	return db.NewTxManager(dbConn)
}

// provideHTTPServer creates an HTTP server.
func provideHTTPServer(cfg *config.Config, handler http.Handler) server.Server {
	srv := server.New(server.Options{
		Address:      cfg.HttpServer.Address(),
		Handler:      handler,
		ReadTimeout:  cfg.HttpServer.ReadTimeout,
		WriteTimeout: cfg.HttpServer.WriteTimeout,
		IdleTimeout:  cfg.HttpServer.IdleTimeout,
	})
	return *srv
}

// provideUserRepository creates a user repository.
func provideUserRepository(dbConn *sql.DB) *repository.Repository {
	return repository.NewRepository(dbConn)
}

// providePhoneValidationRepository creates a phone validation repository.
func providePhoneValidationRepository(dbConn *sql.DB) service.PhoneValidationRepository {
	return repository.NewPhoneValidationRepository(dbConn)
}

// providePhoneValidationService creates a phone validation service.
func providePhoneValidationService(repo service.PhoneValidationRepository) *service.PhoneValidationService {
	return service.NewPhoneValidationService(repo)
}

// provideRegistrationTokenRepository creates a registration token repository.
func provideRegistrationTokenRepository(dbConn *sql.DB) service.RegistrationTokenRepository {
	return repository.NewRegistrationTokenRepository(dbConn)
}

// provideRegistrationTokenService creates a registration token service.
func provideRegistrationTokenService(repo service.RegistrationTokenRepository) *service.RegistrationTokenService {
	return service.NewRegistrationTokenService(repo)
}

// provideRegistrationTokenAdapter creates a registration token adapter.
func provideRegistrationTokenAdapter(service2 *service.RegistrationTokenService) *basic.RegistrationTokenAdapter {
	return basic.NewRegistrationTokenAdapter(service2)
}

// provideUserService creates a user service.
func provideUserService(repo *repository.Repository, roleRepo *role.RoleRepository, phoneValidation *service.PhoneValidationService, registrationTokenService *service.RegistrationTokenService) *service.Service {
	return service.NewService(repo, roleRepo, phoneValidation, registrationTokenService)
}

// provideUserHandler creates a user HTTP handler.
func provideUserHandler(userService *service.Service, permissionChecker *service.UserPermissionChecker) *user.UserHandler {
	return user.NewUserHandler(userService, permissionChecker)
}

// provideCustomerRepository creates a customer repository.
func provideCustomerRepository(dbConn *sql.DB) *customer.CustomerRepository {
	return customer.NewCustomerRepository(dbConn)
}

// provideCustomerService creates a customer service.
func provideCustomerService(repo *customer.CustomerRepository) *customer2.CustomerService {
	return customer2.NewCustomerService(repo)
}

// provideCustomerHandler creates a customer HTTP handler.
func provideCustomerHandler(service2 *customer2.CustomerService) *http2.CustomerHandler {
	return http2.NewCustomerHandler(service2)
}

// provideProductRepository creates a product repository.
func provideProductRepository(dbConn *sql.DB) *repository2.Repository {
	return repository2.NewRepository(dbConn)
}

// provideProductService creates a product service.
func provideProductService(repo *repository2.Repository) *service2.Service {
	return service2.NewService(repo)
}

// provideProductHandler creates a product HTTP handler.
func provideProductHandler(service3 *service2.Service) *http3.ProductHandler {
	return http3.NewProductHandler(service3)
}

// provideOrderRepository creates an order repository.
func provideOrderRepository(dbConn *sql.DB) *repository3.Repository {
	return repository3.NewRepository(dbConn)
}

// provideOrderService creates an order service.
func provideOrderService(repo *repository3.Repository) *order.Service {
	return order.NewService(repo)
}

// provideOrderHandler creates an order HTTP handler.
func provideOrderHandler(service3 *order.Service) *http4.OrderHandler {
	return http4.NewOrderHandler(service3)
}

// provideRoleRepository creates a role repository.
func provideRoleRepository(dbConn *sql.DB, txManager db.TxManager) *role.RoleRepository {
	return role.NewRoleRepository(dbConn, txManager)
}

// provideRoleService creates a role service.
func provideRoleService(repo *role.RoleRepository, permRepo *permission.PermissionRepository) *role2.RoleService {
	return role2.NewRoleService(repo, permRepo)
}

// provideRoleHandler creates a role HTTP handler.
func provideRoleHandler(roleService *role2.RoleService) *role3.RoleHandler {
	return role3.NewRoleHandler(roleService)
}

// providePermissionRepository creates a permission repository.
func providePermissionRepository(dbConn *sql.DB) *permission.PermissionRepository {
	return permission.NewPermissionRepository(dbConn)
}

// providePermissionService creates a permission service.
func providePermissionService(repo *permission.PermissionRepository, resourceService *resource.Service) *permission2.PermissionService {
	return permission2.NewPermissionService(repo, resourceService)
}

// providePermissionHandler creates a permission HTTP handler.
func providePermissionHandler(service3 *permission2.PermissionService) *http5.PermissionHandler {
	return http5.NewPermissionHandler(service3)
}

// provideResourceRepository creates a resource repository.
func provideResourceRepository(dbConn *sql.DB, txManager db.TxManager) *resource2.Repository {
	return resource2.NewRepository(dbConn, txManager)
}

// provideResourceService creates a resource service.
func provideResourceService(repo *resource2.Repository) *resource.Service {
	return resource.NewService(repo)
}

// provideIdempotencyStore wires the idempotency store.
func provideIdempotencyStore(dbConn *sql.DB) *idempotency.Store {
	return idempotency.NewStore(dbConn)
}

// provideIdempotencyMiddleware wires the idempotency middleware.
func provideIdempotencyMiddleware(store *idempotency.Store) *middleware.IdempotencyMiddleware {
	return middleware.NewIdempotencyMiddleware(store)
}

// provideBasicAuthRepository creates a basic auth credential repository.
func provideBasicAuthRepository(dbConn *sql.DB) *repository4.CredentialRepository {
	return repository4.NewCredentialRepository(dbConn)
}

// provideUserPermissionChecker creates a permission checker for auth service.
func provideUserPermissionChecker(userRepo *repository.Repository, roleService *role2.RoleService) *service.UserPermissionChecker {
	return service.NewUserPermissionChecker(userRepo, roleService)
}

// provideBasicAuthService creates a basic auth service.
func provideBasicAuthService(repo *repository4.CredentialRepository, userService *service.Service, permissionChecker *service.UserPermissionChecker) *service3.Service {
	return service3.NewService(repo, userService, permissionChecker)
}

// provideBasicAuthAdapter creates an adapter for the basic auth service.
func provideBasicAuthAdapter(service4 *service3.Service) *basic.Adapter {
	return basic.NewAdapter(service4)
}

// provideBasicAuthHandler creates a basic auth credential handler.
func provideBasicAuthHandler(service4 *service3.Service) *http6.Handler {
	return http6.NewHandler(service4)
}

// provideRegistrationTokenMiddleware creates middleware for validating registration tokens.
func provideRegistrationTokenMiddleware(adapter *basic.RegistrationTokenAdapter) *middleware.RegistrationTokenMiddleware {
	return middleware.NewRegistrationTokenMiddleware(adapter, []string{"/auth/basic/credentials"})
}

// collectPublicRoutes collects public routes from all registered modules.
func collectPublicRoutes() []string {
	return middleware.CollectPublicRoutes()
}

// collectAuthenticatedRoutes collects authenticated routes from all registered modules.
func collectAuthenticatedRoutes() []string {
	return middleware.CollectAuthenticatedRoutes()
}

// provideAuthMiddleware wires the authentication middleware.
func provideAuthMiddleware(cfg *config.Config, basicAuthAdapter *basic.Adapter, userService *service.Service) *middleware.AuthMiddleware {
	realm := "Restricted"
	if cfg.Auth.Basic != nil && cfg.Auth.Basic.Realm != "" {
		realm = cfg.Auth.Basic.Realm
	}

	var basicAuthService middleware.BasicAuthService
	if cfg.Auth.Mode == string(auth.AuthModeBasic) {
		basicAuthService = basicAuthAdapter
	}

	publicRoutes := collectPublicRoutes()
	return middleware.NewAuthMiddleware(auth.AuthMode(cfg.Auth.Mode), realm, basicAuthService, userService, publicRoutes)
}

// provideAuthorizationMiddleware wires the authorization middleware.
func provideAuthorizationMiddleware(resourceService *resource.Service, permissionChecker *service.UserPermissionChecker) *middleware.AuthorizationMiddleware {
	publicRoutes := collectPublicRoutes()
	allowedAuthenticatedRoutes := collectAuthenticatedRoutes()
	return middleware.NewAuthorizationMiddleware(resourceService, permissionChecker, publicRoutes, allowedAuthenticatedRoutes)
}

type httpMiddleware struct {
	idempotencyMiddleware       *middleware.IdempotencyMiddleware
	authMiddleware              *middleware.AuthMiddleware
	authorizationMiddleware     *middleware.AuthorizationMiddleware
	registrationTokenMiddleware *middleware.RegistrationTokenMiddleware
}

// provideHTTPMiddleware creates the httpMiddleware struct.
func provideHTTPMiddleware(idempotencyMiddleware *middleware.IdempotencyMiddleware, authMiddleware *middleware.AuthMiddleware, authorizationMiddleware *middleware.AuthorizationMiddleware, registrationTokenMiddleware *middleware.RegistrationTokenMiddleware) httpMiddleware {
	return httpMiddleware{
		idempotencyMiddleware:       idempotencyMiddleware,
		authMiddleware:              authMiddleware,
		authorizationMiddleware:     authorizationMiddleware,
		registrationTokenMiddleware: registrationTokenMiddleware,
	}
}

// provideHTTPHandler registers HTTP routes and returns a handler.
func provideHTTPHandler(userHandler *user.UserHandler, roleHandler *role3.RoleHandler, permHandler *http5.PermissionHandler, basicAuthHandler *http6.Handler, customerHandler *http2.CustomerHandler, productHandler *http3.ProductHandler, orderHandler *http4.OrderHandler, mw httpMiddleware) http.Handler {
	mux := http.NewServeMux()
	user.RegisterHTTPRoutes(mux, userHandler)
	role3.RegisterHTTPRoutes(mux, roleHandler)
	http5.RegisterHTTPRoutes(mux, permHandler)
	http6.RegisterHTTPRoutes(mux, basicAuthHandler)
	http2.RegisterHTTPRoutes(mux, customerHandler)
	http3.RegisterHTTPRoutes(mux, productHandler)
	http4.RegisterHTTPRoutes(mux, orderHandler)

	handler := mw.idempotencyMiddleware.Handle(mux)
	handler = mw.authorizationMiddleware.Handle(handler)
	handler = mw.authMiddleware.Handle(handler)
	handler = mw.registrationTokenMiddleware.Handle(handler)
	loggingMiddleware := middleware.NewLoggingMiddleware()
	handler = loggingMiddleware.Log(handler)
	handler = middleware.RequestIDMiddleware(handler)
	return handler
}

type applicationServices struct {
	userService      *service.Service
	roleService      *role2.RoleService
	permService      *permission2.PermissionService
	resourceService  *resource.Service
	basicAuthService *service3.Service
	customerService  *customer2.CustomerService
	productService   *service2.Service
	orderService     *order.Service
}

type applicationHandlers struct {
	userHandler     *user.UserHandler
	roleHandler     *role3.RoleHandler
	permHandler     *http5.PermissionHandler
	customerHandler *http2.CustomerHandler
	productHandler  *http3.ProductHandler
	orderHandler    *http4.OrderHandler
}

type applicationInfrastructure struct {
	cfg    *config.Config
	db     *sql.DB
	server server.Server
}

func provideApplicationInfrastructure(cfg *config.Config, dbConn *sql.DB, server2 server.Server) applicationInfrastructure {
	return applicationInfrastructure{
		cfg:    cfg,
		db:     dbConn,
		server: server2,
	}
}

func provideApplicationServices(userService *service.Service, roleService *role2.RoleService, permService *permission2.PermissionService, resourceService *resource.Service, basicAuthService *service3.Service, customerService *customer2.CustomerService, productService *service2.Service, orderService *order.Service) applicationServices {
	return applicationServices{
		userService:      userService,
		roleService:      roleService,
		permService:      permService,
		resourceService:  resourceService,
		basicAuthService: basicAuthService,
		customerService:  customerService,
		productService:   productService,
		orderService:     orderService,
	}
}

func provideApplicationHandlers(userHandler *user.UserHandler, roleHandler *role3.RoleHandler, permHandler *http5.PermissionHandler, customerHandler *http2.CustomerHandler, productHandler *http3.ProductHandler, orderHandler *http4.OrderHandler) applicationHandlers {
	return applicationHandlers{
		userHandler:     userHandler,
		roleHandler:     roleHandler,
		permHandler:     permHandler,
		customerHandler: customerHandler,
		productHandler:  productHandler,
		orderHandler:    orderHandler,
	}
}

func provideApplication(infra applicationInfrastructure, services applicationServices, handlers applicationHandlers) *Application {
	return &Application{
		Config:           infra.cfg,
		DB:               infra.db,
		Server:           infra.server,
		UserService:      services.userService,
		UserHandler:      handlers.userHandler,
		RoleService:      services.roleService,
		RoleHandler:      handlers.roleHandler,
		PermService:      services.permService,
		PermHandler:      handlers.permHandler,
		ResourceService:  services.resourceService,
		BasicAuthService: services.basicAuthService,
		CustomerService:  services.customerService,
		CustomerHandler:  handlers.customerHandler,
		ProductService:   services.productService,
		ProductHandler:   handlers.productHandler,
		OrderService:     services.orderService,
		OrderHandler:     handlers.orderHandler,
	}
}
