package resourcegen

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	resourceDomain "marketplace/internal/infra/authz/resource/domain"

	"gopkg.in/yaml.v3"
)

const (
	resourceAnnotationPrefix = "@resource"
	actionAnnotationPrefix   = "@action"
)

// manifestFile mirrors the structure of config/resources.yaml.
type manifestFile struct {
	Resources []resourceDomain.ManifestResource `yaml:"resources"`
}

// Generate builds the resource manifest by scanning HTTP route annotations
// and writes it into a YAML manifest at outPath.
func Generate(outPath string) error {
	resources, err := scanManifestFromRoutes()
	if err != nil {
		return fmt.Errorf("scan manifest from routes: %w", err)
	}

	data := manifestFile{
		Resources: resources,
	}

	bytes, err := yaml.Marshal(&data)
	if err != nil {
		return fmt.Errorf("marshal resources manifest: %w", err)
	}

	// Prepend a short header comment to match the existing file semantics.
	header := []byte("# Resource Manifest\n" +
		"# This file is generated from HTTP route annotations.\n" +
		"# Do NOT edit this file manually; instead, update the annotations and re-run the generator.\n\n")

	if err := os.WriteFile(outPath, append(header, bytes...), 0o644); err != nil {
		return fmt.Errorf("write resources manifest to %s: %w", outPath, err)
	}

	return nil
}

// scanManifestFromRoutes automatically discovers all Go files containing @resource annotations
// and builds the manifest resources from them.
func scanManifestFromRoutes() ([]resourceDomain.ManifestResource, error) {
	routeFiles, err := discoverRouteFiles("internal")
	if err != nil {
		return nil, fmt.Errorf("discover route files: %w", err)
	}

	var resources []resourceDomain.ManifestResource
	for _, path := range routeFiles {
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}

		fileResources, err := resourcesFromFile(fset, file)
		if err != nil {
			return nil, fmt.Errorf("extract resources from %s: %w", path, err)
		}
		resources = append(resources, fileResources...)
	}

	return resources, nil
}

// discoverRouteFiles walks the directory tree starting from rootDir and finds all Go files
// that contain @resource annotations.
func discoverRouteFiles(rootDir string) ([]string, error) {
	var routeFiles []string

	err := filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Skip directories, non-Go files, and test files
		if info.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_test.go") {
			return nil
		}

		// Check if file contains @resource annotation
		hasResource, err := fileContainsResourceAnnotation(path)
		if err != nil {
			return fmt.Errorf("check %s: %w", path, err)
		}

		if hasResource {
			routeFiles = append(routeFiles, path)
		}

		return nil
	})

	return routeFiles, err
}

// fileContainsResourceAnnotation checks if a file contains @resource annotation
// by reading and scanning its content.
func fileContainsResourceAnnotation(filePath string) (bool, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return false, err
	}

	content := string(data)
	lines := strings.Split(content, "\n")

	for _, line := range lines {
		// Check for @resource annotation in comments
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "//") {
			comment := strings.TrimSpace(strings.TrimPrefix(trimmed, "//"))
			if strings.HasPrefix(comment, resourceAnnotationPrefix) {
				return true, nil
			}
		}
	}

	return false, nil
}

// annotation represents a parsed @resource or @action annotation with its position.
type annotation struct {
	pos        token.Pos
	text       string
	isResource bool
}

// resourcesFromFile reads @resource and @action annotations from the comment
// groups in the given file. A file can contain multiple resources.
// Comments are processed in file order using position information.
func resourcesFromFile(fset *token.FileSet, f *ast.File) ([]resourceDomain.ManifestResource, error) {
	var annotations []annotation

	// Collect all annotations with their positions
	for _, cg := range f.Comments {
		for _, c := range cg.List {
			text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			if !strings.HasPrefix(text, "@") {
				continue
			}

			isResource := strings.HasPrefix(text, resourceAnnotationPrefix)
			isAction := strings.HasPrefix(text, actionAnnotationPrefix)
			if isResource || isAction {
				annotations = append(annotations, annotation{
					pos:        c.Pos(),
					text:       text,
					isResource: isResource,
				})
			}
		}
	}

	// Sort annotations by position in file
	sort.Slice(annotations, func(i, j int) bool {
		return fset.Position(annotations[i].pos).Offset < fset.Position(annotations[j].pos).Offset
	})

	// Process annotations in file order
	resourceMap := make(map[string]*resourceDomain.ManifestResource)
	var currentCode string

	for _, ann := range annotations {
		text := ann.text

		switch {
		case ann.isResource:
			args := strings.TrimSpace(strings.TrimPrefix(text, resourceAnnotationPrefix))
			kv := parseAnnotationArgs(args)
			code := kv["code"]
			currentCode = code
			
			// Check if resource with this code already exists
			if _, exists := resourceMap[code]; !exists {
				res := resourceDomain.ManifestResource{
					Code:        code,
					Service:     kv["service"],
					Description: kv["desc"],
				}
				resourceMap[code] = &res
			}

		case strings.HasPrefix(text, actionAnnotationPrefix):
			if currentCode == "" {
				return nil, fmt.Errorf("@action annotation without @resource")
			}
			current, exists := resourceMap[currentCode]
			if !exists {
				return nil, fmt.Errorf("@action annotation for unknown resource: %s", currentCode)
			}
			args := strings.TrimSpace(strings.TrimPrefix(text, actionAnnotationPrefix))
			kv := parseAnnotationArgs(args)
			act := resourceDomain.ManifestAction{
				Name:        kv["name"],
				Description: kv["desc"],
			}
			current.Actions = append(current.Actions, act)
		}
	}

	// Convert map to slice
	var resources []resourceDomain.ManifestResource
	for _, res := range resourceMap {
		resources = append(resources, *res)
	}

	return resources, nil
}

// parseAnnotationArgs parses a string of the form `key=value key2="value 2"`
// into a map. It is intentionally minimal and only supports double-quoted
// values for keys that contain spaces.
func parseAnnotationArgs(s string) map[string]string {
	result := make(map[string]string)
	for _, part := range splitArgs(strings.TrimSpace(s)) {
		if part == "" {
			continue
		}
		eq := strings.Index(part, "=")
		if eq <= 0 {
			continue
		}
		key := strings.TrimSpace(part[:eq])
		val := strings.TrimSpace(part[eq+1:])
		val = strings.Trim(val, `"`)
		result[key] = val
	}
	return result
}

// splitArgs splits on spaces while keeping segments wrapped in double quotes
// together (e.g. `desc="My description"` is preserved as one token).
func splitArgs(s string) []string {
	var parts []string
	var buf strings.Builder
	inQuotes := false

	for _, r := range s {
		switch r {
		case '"':
			inQuotes = !inQuotes
			buf.WriteRune(r)
		case ' ', '\t':
			if inQuotes {
				buf.WriteRune(r)
			} else if buf.Len() > 0 {
				parts = append(parts, buf.String())
				buf.Reset()
			}
		default:
			buf.WriteRune(r)
		}
	}
	if buf.Len() > 0 {
		parts = append(parts, buf.String())
	}
	return parts
}
